[package]
name = "lexer"
version = "0.1.0"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]
build = "build.rs"

[dependencies]
peg-syntax-ext = "0.5.0"

[build-dependencies]
peg = { version = "0.5" }
